version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ConnectionString: Host=db;Port=5432;Database=library;user Id=root;Password=root;Include Error Detail=true
    ports:
      - "8090:80"
    depends_on:
      - db
volumes:
  db_data:
